# --- Trials ---
training_trials: [
                  [{n_trials: 0, task_type: memory, stimulus_type: arrow, n_elements: 2},
                   {n_trials: 0, task_type: relational, stimulus_type: figure, n_elements: 3}],
                  [{n_trials: 10, task_type: memory, stimulus_type: figure, n_elements: 4}]
]

experiment_trials: [
                  [{n_trials: 5, task_type: memory, stimulus_type: arrow, n_elements: 2},
                   {n_trials: 5, task_type: relational, stimulus_type: figure, n_elements: 3}],
                  [{n_trials: 10, task_type: memory, stimulus_type: figure, n_elements: 4}]
]

# --- Timing ---
matrix_1_time: 2 # in seconds
matrix_2_time: 6 # in seconds
matrix_3_time: 1 # in seconds
matrix_4_time: 4 # in seconds; or until participant will chose answer


# --- Stimulus visual---
stimulus_color: black

## figures
dot_size: 3
figure_size: 15
stimulus_figure_width: 2

## arrows
arrow_size: 3
stimulus_arrow_width: 2

## mask
mask_dot_size: 15

## underline
underline_color: red
underline_width: 1
underline_extra_size: 7

# --- Figures Sets Visual ---
stimulus_center: [0, 0]
stimulus_distance_from_center: 100

## hit-area (mouse click detection for matrix_4)
hit_area_size: 100            # Side length of the invisible click rectangle (px)
hit_area_show_hover: true    # If true, hit-area becomes visible on mouse hover
hit_area_hover_color: black  # Border color when hovered
hit_area_hover_fill: null    # Fill color when hovered (null = transparent)
hit_area_hover_width: 10      # Border width when hovered (px)

# --- Monitor Settings ---
monitor_name: "defaultMonitor"     # Name of the monitor profile in PsychoPy
monitor_width: 53.0                # Physical width of the screen in cm
monitor_distance: 60.0             # Distance from the participant to the screen in cm

# --- Window Settings ---
screen_color: "gray"              # Background color of the experiment window

# --- Fixation Cross ---
fixation_color: "white"            # Color of the fixation stimulus
fixation_text: "+"                 # Character used for fixation
fixation_size: 40                  # Height in pixels (since units='pix' in main.py)
fixation_time: 1                   # In seconds

# --- Feedback Settings ---
feedback_training: True            # if feedback should be shown during training
feedback_experiment: False         # if feedback should be shown during experiment
feedback_text: {
  1: "Dobrze",               # Message for accurate response
  0: "Błędnie",              # Message for inaccurate response
  -1: "Brak odpowiedzi"}     # Message for no response
feedback_color: "white"      # Color of the feedback text
feedback_size: 24            # Height of the feedback text in pixels
feedback_time: 1             # Duration of feedback display in seconds

# --- Instruction Settings ---
instruction_color: "white"         # Default color for instruction text
instruction_text_size: 24          # Default height for instruction text
instruction_wrap_width: 800        # Maximum line width before wrapping in pixels
instruction_font: 'Segoe UI Emoji' # Font name of the displayed text

# --- Trigger Settings ---
trigger:
  dummy_mode: true        # false = wysyłaj sygnały do EEG
  trigger_time: 0.004     # trigger time in s
  trigger_limit: 60       # maks trigger value (triggers will be sent in a loop from 1 to trigger_limit)
  trigger_params:         # extra columns in trigger_map
    - block_type
    - acc
    - trial_type